#!/usr/bin/env bash
set -euo pipefail

WORKDIR="${DEPLOY_WORKDIR:-/opt/erp-retail}"
BRANCH="${DEPLOY_BRANCH:-main}"
ENV_FILE="${DEPLOY_ENV_FILE:-$WORKDIR/.deploy.env}"

echo "[deploy] workdir=$WORKDIR branch=$BRANCH env_file=$ENV_FILE"

if [ ! -d "$WORKDIR/.git" ]; then
  echo "[deploy] missing git repo at $WORKDIR"
  exit 1
fi

cd "$WORKDIR"

echo "[deploy] fetch latest"
git fetch origin "$BRANCH"
git checkout "$BRANCH"
git reset --hard "origin/$BRANCH"

require_single_line_env() {
  local name="$1"
  local value="$2"
  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    echo "[deploy] invalid $name: multiline values are not allowed"
    exit 1
  fi
}

NODE_ENV_VALUE="${NODE_ENV:-production}"
AUTH_ENABLED_VALUE="${AUTH_ENABLED:-false}"
NEXT_PUBLIC_AUTH_ENABLED_VALUE="${NEXT_PUBLIC_AUTH_ENABLED:-false}"
PERMISSION_ENGINE_ENABLED_VALUE="${PERMISSION_ENGINE_ENABLED:-false}"
IAM_V2_ENABLED_VALUE="${IAM_V2_ENABLED:-}"
DATABASE_URL_VALUE="${DATABASE_URL:-postgresql://erp:erp@postgres:5432/erp_retail}"
REDIS_URL_VALUE="${REDIS_URL:-redis://redis:6379}"
DEFAULT_TENANT_ID_VALUE="${DEFAULT_TENANT_ID:-GOIUUDAI}"
TENANCY_MODE_VALUE="${TENANCY_MODE:-single}"
API_PORT_VALUE="${API_PORT:-3001}"
WEB_PORT_VALUE="${WEB_PORT:-3000}"
NEXT_PUBLIC_API_BASE_URL_VALUE="${NEXT_PUBLIC_API_BASE_URL:-http://api:3001/api/v1}"
AI_OPENAI_COMPAT_BASE_URL_VALUE="${AI_OPENAI_COMPAT_BASE_URL:-}"
AI_OPENAI_COMPAT_API_KEY_VALUE="${AI_OPENAI_COMPAT_API_KEY:-}"
AI_OPENAI_COMPAT_MODEL_VALUE="${AI_OPENAI_COMPAT_MODEL:-gpt-4o-mini}"
AI_OPENAI_COMPAT_TIMEOUT_MS_VALUE="${AI_OPENAI_COMPAT_TIMEOUT_MS:-45000}"
BHTOT_API_KEY_VALUE="${BHTOT_API_KEY:-}"
SETTINGS_ENCRYPTION_MASTER_KEY_VALUE="${SETTINGS_ENCRYPTION_MASTER_KEY:-}"
ZALO_OA_WEBHOOK_SECRET_VALUE="${ZALO_OA_WEBHOOK_SECRET:-}"
ZALO_OA_OUTBOUND_URL_VALUE="${ZALO_OA_OUTBOUND_URL:-}"
ZALO_OA_ACCESS_TOKEN_VALUE="${ZALO_OA_ACCESS_TOKEN:-}"
ZALO_OA_API_BASE_URL_VALUE="${ZALO_OA_API_BASE_URL:-https://openapi.zalo.me/v3.0/oa}"
ZALO_OA_OUTBOUND_TIMEOUT_MS_VALUE="${ZALO_OA_OUTBOUND_TIMEOUT_MS:-20000}"
SEARCH_ENGINE_VALUE="${SEARCH_ENGINE:-sql}"
MEILI_HOST_VALUE="${MEILI_HOST:-http://meilisearch:7700}"
MEILI_MASTER_KEY_VALUE="${MEILI_MASTER_KEY:-}"
MEILI_INDEX_PREFIX_VALUE="${MEILI_INDEX_PREFIX:-erp}"
MEILI_TIMEOUT_MS_VALUE="${MEILI_TIMEOUT_MS:-45000}"
MEILI_ENABLE_WRITE_SYNC_VALUE="${MEILI_ENABLE_WRITE_SYNC:-false}"
MEILI_PORT_VALUE="${MEILI_PORT:-7700}"
AUDIT_ARCHIVE_S3_ENDPOINT_VALUE="${AUDIT_ARCHIVE_S3_ENDPOINT:-http://minio:9000}"
AUDIT_ARCHIVE_S3_BUCKET_VALUE="${AUDIT_ARCHIVE_S3_BUCKET:-erp-audit-archive}"
AUDIT_ARCHIVE_S3_REGION_VALUE="${AUDIT_ARCHIVE_S3_REGION:-us-east-1}"
AUDIT_ARCHIVE_S3_ACCESS_KEY_VALUE="${AUDIT_ARCHIVE_S3_ACCESS_KEY:-erpminio}"
AUDIT_ARCHIVE_S3_SECRET_KEY_VALUE="${AUDIT_ARCHIVE_S3_SECRET_KEY:-REPLACE_WITH_SECURE_MINIO_PASSWORD}"
AUDIT_ARCHIVE_S3_FORCE_PATH_STYLE_VALUE="${AUDIT_ARCHIVE_S3_FORCE_PATH_STYLE:-true}"
AUDIT_ARCHIVE_S3_TLS_ENABLED_VALUE="${AUDIT_ARCHIVE_S3_TLS_ENABLED:-false}"
AUDIT_MAINTENANCE_SCHEDULER_ENABLED_VALUE="${AUDIT_MAINTENANCE_SCHEDULER_ENABLED:-true}"
AUDIT_MAINTENANCE_SCHEDULER_UTC_HOUR_VALUE="${AUDIT_MAINTENANCE_SCHEDULER_UTC_HOUR:-19}"
AUDIT_COLD_QUERY_MAX_DAYS_VALUE="${AUDIT_COLD_QUERY_MAX_DAYS:-31}"
MINIO_PORT_VALUE="${MINIO_PORT:-9000}"
MINIO_CONSOLE_PORT_VALUE="${MINIO_CONSOLE_PORT:-9001}"
MINIO_ROOT_USER_VALUE="${MINIO_ROOT_USER:-erpminio}"
MINIO_ROOT_PASSWORD_VALUE="${MINIO_ROOT_PASSWORD:-REPLACE_WITH_SECURE_MINIO_PASSWORD}"
POST_DEPLOY_AUTH_RBAC_SMOKE_ENABLED_VALUE="${POST_DEPLOY_AUTH_RBAC_SMOKE_ENABLED:-false}"
POST_DEPLOY_AUTH_RBAC_SMOKE_MODULES_VALUE="${POST_DEPLOY_AUTH_RBAC_SMOKE_MODULES:-}"
JWT_SECRET_VALUE="${JWT_SECRET:-}"

if [ "$AUTH_ENABLED_VALUE" = "true" ] && { [ -z "$JWT_SECRET_VALUE" ] || [ "$JWT_SECRET_VALUE" = "change_me_to_a_long_secret" ]; }; then
  echo "[deploy] error: AUTH_ENABLED=true requires a non-default JWT_SECRET."
  exit 1
fi
JWT_SECRET_VALUE="${JWT_SECRET_VALUE:-change_me_to_a_long_secret}"

if [ "$NEXT_PUBLIC_AUTH_ENABLED_VALUE" = "true" ] && [ "$AUTH_ENABLED_VALUE" != "true" ]; then
  echo "[deploy] warning: NEXT_PUBLIC_AUTH_ENABLED=true but AUTH_ENABLED!=true. UI may enforce login while API auth is disabled."
fi

if [ -z "$SETTINGS_ENCRYPTION_MASTER_KEY_VALUE" ]; then
  echo "[deploy] warning: SETTINGS_ENCRYPTION_MASTER_KEY is empty; secrets entered in Settings Center cannot be encrypted at rest."
fi

require_single_line_env "NODE_ENV" "$NODE_ENV_VALUE"
require_single_line_env "AUTH_ENABLED" "$AUTH_ENABLED_VALUE"
require_single_line_env "NEXT_PUBLIC_AUTH_ENABLED" "$NEXT_PUBLIC_AUTH_ENABLED_VALUE"
require_single_line_env "PERMISSION_ENGINE_ENABLED" "$PERMISSION_ENGINE_ENABLED_VALUE"
require_single_line_env "IAM_V2_ENABLED" "$IAM_V2_ENABLED_VALUE"
require_single_line_env "DATABASE_URL" "$DATABASE_URL_VALUE"
require_single_line_env "REDIS_URL" "$REDIS_URL_VALUE"
require_single_line_env "DEFAULT_TENANT_ID" "$DEFAULT_TENANT_ID_VALUE"
require_single_line_env "TENANCY_MODE" "$TENANCY_MODE_VALUE"
require_single_line_env "API_PORT" "$API_PORT_VALUE"
require_single_line_env "WEB_PORT" "$WEB_PORT_VALUE"
require_single_line_env "NEXT_PUBLIC_API_BASE_URL" "$NEXT_PUBLIC_API_BASE_URL_VALUE"
require_single_line_env "JWT_SECRET" "$JWT_SECRET_VALUE"
require_single_line_env "AI_OPENAI_COMPAT_BASE_URL" "$AI_OPENAI_COMPAT_BASE_URL_VALUE"
require_single_line_env "AI_OPENAI_COMPAT_API_KEY" "$AI_OPENAI_COMPAT_API_KEY_VALUE"
require_single_line_env "AI_OPENAI_COMPAT_MODEL" "$AI_OPENAI_COMPAT_MODEL_VALUE"
require_single_line_env "AI_OPENAI_COMPAT_TIMEOUT_MS" "$AI_OPENAI_COMPAT_TIMEOUT_MS_VALUE"
require_single_line_env "BHTOT_API_KEY" "$BHTOT_API_KEY_VALUE"
require_single_line_env "SETTINGS_ENCRYPTION_MASTER_KEY" "$SETTINGS_ENCRYPTION_MASTER_KEY_VALUE"
require_single_line_env "ZALO_OA_WEBHOOK_SECRET" "$ZALO_OA_WEBHOOK_SECRET_VALUE"
require_single_line_env "ZALO_OA_OUTBOUND_URL" "$ZALO_OA_OUTBOUND_URL_VALUE"
require_single_line_env "ZALO_OA_ACCESS_TOKEN" "$ZALO_OA_ACCESS_TOKEN_VALUE"
require_single_line_env "ZALO_OA_API_BASE_URL" "$ZALO_OA_API_BASE_URL_VALUE"
require_single_line_env "ZALO_OA_OUTBOUND_TIMEOUT_MS" "$ZALO_OA_OUTBOUND_TIMEOUT_MS_VALUE"
require_single_line_env "SEARCH_ENGINE" "$SEARCH_ENGINE_VALUE"
require_single_line_env "MEILI_HOST" "$MEILI_HOST_VALUE"
require_single_line_env "MEILI_MASTER_KEY" "$MEILI_MASTER_KEY_VALUE"
require_single_line_env "MEILI_INDEX_PREFIX" "$MEILI_INDEX_PREFIX_VALUE"
require_single_line_env "MEILI_TIMEOUT_MS" "$MEILI_TIMEOUT_MS_VALUE"
require_single_line_env "MEILI_ENABLE_WRITE_SYNC" "$MEILI_ENABLE_WRITE_SYNC_VALUE"
require_single_line_env "MEILI_PORT" "$MEILI_PORT_VALUE"
require_single_line_env "AUDIT_ARCHIVE_S3_ENDPOINT" "$AUDIT_ARCHIVE_S3_ENDPOINT_VALUE"
require_single_line_env "AUDIT_ARCHIVE_S3_BUCKET" "$AUDIT_ARCHIVE_S3_BUCKET_VALUE"
require_single_line_env "AUDIT_ARCHIVE_S3_REGION" "$AUDIT_ARCHIVE_S3_REGION_VALUE"
require_single_line_env "AUDIT_ARCHIVE_S3_ACCESS_KEY" "$AUDIT_ARCHIVE_S3_ACCESS_KEY_VALUE"
require_single_line_env "AUDIT_ARCHIVE_S3_SECRET_KEY" "$AUDIT_ARCHIVE_S3_SECRET_KEY_VALUE"
require_single_line_env "AUDIT_ARCHIVE_S3_FORCE_PATH_STYLE" "$AUDIT_ARCHIVE_S3_FORCE_PATH_STYLE_VALUE"
require_single_line_env "AUDIT_ARCHIVE_S3_TLS_ENABLED" "$AUDIT_ARCHIVE_S3_TLS_ENABLED_VALUE"
require_single_line_env "AUDIT_MAINTENANCE_SCHEDULER_ENABLED" "$AUDIT_MAINTENANCE_SCHEDULER_ENABLED_VALUE"
require_single_line_env "AUDIT_MAINTENANCE_SCHEDULER_UTC_HOUR" "$AUDIT_MAINTENANCE_SCHEDULER_UTC_HOUR_VALUE"
require_single_line_env "AUDIT_COLD_QUERY_MAX_DAYS" "$AUDIT_COLD_QUERY_MAX_DAYS_VALUE"
require_single_line_env "MINIO_PORT" "$MINIO_PORT_VALUE"
require_single_line_env "MINIO_CONSOLE_PORT" "$MINIO_CONSOLE_PORT_VALUE"
require_single_line_env "MINIO_ROOT_USER" "$MINIO_ROOT_USER_VALUE"
require_single_line_env "MINIO_ROOT_PASSWORD" "$MINIO_ROOT_PASSWORD_VALUE"
require_single_line_env "POST_DEPLOY_AUTH_RBAC_SMOKE_ENABLED" "$POST_DEPLOY_AUTH_RBAC_SMOKE_ENABLED_VALUE"
require_single_line_env "POST_DEPLOY_AUTH_RBAC_SMOKE_MODULES" "$POST_DEPLOY_AUTH_RBAC_SMOKE_MODULES_VALUE"

echo "[deploy] write runtime env file"
umask 077
cat >"$ENV_FILE" <<EOF
NODE_ENV=$NODE_ENV_VALUE
AUTH_ENABLED=$AUTH_ENABLED_VALUE
NEXT_PUBLIC_AUTH_ENABLED=$NEXT_PUBLIC_AUTH_ENABLED_VALUE
PERMISSION_ENGINE_ENABLED=$PERMISSION_ENGINE_ENABLED_VALUE
IAM_V2_ENABLED=$IAM_V2_ENABLED_VALUE
DATABASE_URL=$DATABASE_URL_VALUE
REDIS_URL=$REDIS_URL_VALUE
DEFAULT_TENANT_ID=$DEFAULT_TENANT_ID_VALUE
TENANCY_MODE=$TENANCY_MODE_VALUE
API_PORT=$API_PORT_VALUE
WEB_PORT=$WEB_PORT_VALUE
NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL_VALUE
JWT_SECRET=$JWT_SECRET_VALUE
AI_OPENAI_COMPAT_BASE_URL=$AI_OPENAI_COMPAT_BASE_URL_VALUE
AI_OPENAI_COMPAT_API_KEY=$AI_OPENAI_COMPAT_API_KEY_VALUE
AI_OPENAI_COMPAT_MODEL=$AI_OPENAI_COMPAT_MODEL_VALUE
AI_OPENAI_COMPAT_TIMEOUT_MS=$AI_OPENAI_COMPAT_TIMEOUT_MS_VALUE
BHTOT_API_KEY=$BHTOT_API_KEY_VALUE
SETTINGS_ENCRYPTION_MASTER_KEY=$SETTINGS_ENCRYPTION_MASTER_KEY_VALUE
ZALO_OA_WEBHOOK_SECRET=$ZALO_OA_WEBHOOK_SECRET_VALUE
ZALO_OA_OUTBOUND_URL=$ZALO_OA_OUTBOUND_URL_VALUE
ZALO_OA_ACCESS_TOKEN=$ZALO_OA_ACCESS_TOKEN_VALUE
ZALO_OA_API_BASE_URL=$ZALO_OA_API_BASE_URL_VALUE
ZALO_OA_OUTBOUND_TIMEOUT_MS=$ZALO_OA_OUTBOUND_TIMEOUT_MS_VALUE
SEARCH_ENGINE=$SEARCH_ENGINE_VALUE
MEILI_HOST=$MEILI_HOST_VALUE
MEILI_MASTER_KEY=$MEILI_MASTER_KEY_VALUE
MEILI_INDEX_PREFIX=$MEILI_INDEX_PREFIX_VALUE
MEILI_TIMEOUT_MS=$MEILI_TIMEOUT_MS_VALUE
MEILI_ENABLE_WRITE_SYNC=$MEILI_ENABLE_WRITE_SYNC_VALUE
MEILI_PORT=$MEILI_PORT_VALUE
AUDIT_ARCHIVE_S3_ENDPOINT=$AUDIT_ARCHIVE_S3_ENDPOINT_VALUE
AUDIT_ARCHIVE_S3_BUCKET=$AUDIT_ARCHIVE_S3_BUCKET_VALUE
AUDIT_ARCHIVE_S3_REGION=$AUDIT_ARCHIVE_S3_REGION_VALUE
AUDIT_ARCHIVE_S3_ACCESS_KEY=$AUDIT_ARCHIVE_S3_ACCESS_KEY_VALUE
AUDIT_ARCHIVE_S3_SECRET_KEY=$AUDIT_ARCHIVE_S3_SECRET_KEY_VALUE
AUDIT_ARCHIVE_S3_FORCE_PATH_STYLE=$AUDIT_ARCHIVE_S3_FORCE_PATH_STYLE_VALUE
AUDIT_ARCHIVE_S3_TLS_ENABLED=$AUDIT_ARCHIVE_S3_TLS_ENABLED_VALUE
AUDIT_MAINTENANCE_SCHEDULER_ENABLED=$AUDIT_MAINTENANCE_SCHEDULER_ENABLED_VALUE
AUDIT_MAINTENANCE_SCHEDULER_UTC_HOUR=$AUDIT_MAINTENANCE_SCHEDULER_UTC_HOUR_VALUE
AUDIT_COLD_QUERY_MAX_DAYS=$AUDIT_COLD_QUERY_MAX_DAYS_VALUE
MINIO_PORT=$MINIO_PORT_VALUE
MINIO_CONSOLE_PORT=$MINIO_CONSOLE_PORT_VALUE
MINIO_ROOT_USER=$MINIO_ROOT_USER_VALUE
MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD_VALUE
POST_DEPLOY_AUTH_RBAC_SMOKE_ENABLED=$POST_DEPLOY_AUTH_RBAC_SMOKE_ENABLED_VALUE
POST_DEPLOY_AUTH_RBAC_SMOKE_MODULES=$POST_DEPLOY_AUTH_RBAC_SMOKE_MODULES_VALUE
EOF
chmod 600 "$ENV_FILE"

echo "[deploy] build and restart containers"
docker compose --env-file "$ENV_FILE" build
docker compose --env-file "$ENV_FILE" up -d postgres redis meilisearch minio

echo "[deploy] run prisma migrate deploy"
migrate_ok=0
for i in {1..20}; do
  if docker compose --env-file "$ENV_FILE" run --rm api npx prisma migrate deploy --schema apps/api/prisma/schema.prisma; then
    migrate_ok=1
    break
  fi
  echo "[deploy] migrate attempt $i failed, retrying..."
  sleep 3
done

if [ "$migrate_ok" -ne 1 ]; then
  echo "[deploy] migration failed after retries"
  exit 1
fi

docker compose --env-file "$ENV_FILE" up -d api web

echo "[deploy] run health check"
"$WORKDIR/scripts/deploy/healthcheck.sh"

post_deploy_auth_rbac_smoke_enabled="$(echo "$POST_DEPLOY_AUTH_RBAC_SMOKE_ENABLED_VALUE" | tr '[:upper:]' '[:lower:]')"
if [ "$post_deploy_auth_rbac_smoke_enabled" = "true" ]; then
  echo "[deploy] run post-deploy auth/rbac smoke"
  export SMOKE_API_BASE_URL="http://127.0.0.1:${API_PORT_VALUE}/api/v1"
  export SMOKE_AUTH_ENABLED="$AUTH_ENABLED_VALUE"
  export SMOKE_JWT_SECRET="$JWT_SECRET_VALUE"
  if [ -n "$POST_DEPLOY_AUTH_RBAC_SMOKE_MODULES_VALUE" ]; then
    export SMOKE_ENFORCED_MODULES="$POST_DEPLOY_AUTH_RBAC_SMOKE_MODULES_VALUE"
  else
    unset SMOKE_ENFORCED_MODULES || true
  fi
  "$WORKDIR/scripts/deploy/smoke-auth-rbac-modules.sh"
fi

echo "[deploy] success"
