import process from 'node:process';

type ApiCallOptions = {
  method?: 'GET' | 'POST' | 'PATCH';
  body?: unknown;
  headers?: Record<string, string>;
};

type StepResult = {
  step: string;
  passed: boolean;
  details?: string;
};

function cleanBaseUrl(raw: string) {
  return raw.replace(/\/$/, '');
}

async function apiCall(baseUrl: string, path: string, tenantId: string, token: string | null, options: ApiCallOptions = {}) {
  const headers: Record<string, string> = {
    'content-type': 'application/json',
    'x-tenant-id': tenantId,
    ...(options.headers ?? {})
  };

  if (token) {
    headers.authorization = `Bearer ${token}`;
  }

  const response = await fetch(`${baseUrl}${path}`, {
    method: options.method ?? 'GET',
    headers,
    body: options.body !== undefined ? JSON.stringify(options.body) : undefined,
    cache: 'no-store'
  });

  const text = await response.text();
  let payload: unknown = null;
  if (text) {
    try {
      payload = JSON.parse(text);
    } catch {
      payload = text;
    }
  }

  if (!response.ok) {
    throw new Error(`HTTP ${response.status} ${path} => ${typeof payload === 'string' ? payload : JSON.stringify(payload)}`);
  }

  return payload;
}

function asRecord(value: unknown) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return {} as Record<string, unknown>;
  }
  return value as Record<string, unknown>;
}

async function main() {
  const baseUrl = cleanBaseUrl(String(process.env.WORKFLOW_SMOKE_BASE_URL ?? 'http://127.0.0.1:3001/api/v1').trim());
  const tenantId = String(process.env.WORKFLOW_SMOKE_TENANT_ID ?? process.env.DEFAULT_TENANT_ID ?? 'GOIUUDAI').trim();
  const token = String(process.env.WORKFLOW_SMOKE_AUTH_TOKEN ?? '').trim() || null;

  const uniqueCode = `WF_SMOKE_${Date.now()}`;
  const startedAt = new Date().toISOString();
  const steps: StepResult[] = [];

  const createPayload = {
    code: uniqueCode,
    name: 'Workflow Smoke Lifecycle Check',
    module: 'workflows',
    version: 1,
    description: 'Auto-generated by smoke-workflow-definition-lifecycle.ts',
    status: 'DRAFT',
    definitionJson: {
      initialStep: 'approval',
      steps: [
        {
          key: 'approval',
          name: 'Manager Approval',
          approvalMode: 'ALL',
          minApprovers: 1,
          slaHours: 24,
          approvers: [{ type: 'ROLE', role: 'MANAGER' }],
          transitions: [
            { action: 'APPROVE', terminalStatus: 'APPROVED' },
            { action: 'REJECT', terminalStatus: 'REJECTED' }
          ]
        }
      ]
    }
  };

  const created = asRecord(
    await apiCall(baseUrl, '/workflows/definitions', tenantId, token, {
      method: 'POST',
      body: createPayload
    })
  );

  const definitionId = String(created.id ?? '').trim();
  if (!definitionId) {
    throw new Error('Create definition không trả về id hợp lệ.');
  }
  steps.push({ step: 'create', passed: true, details: `id=${definitionId}` });

  const validated = asRecord(
    await apiCall(baseUrl, `/workflows/definitions/${definitionId}/validate`, tenantId, token, {
      method: 'POST'
    })
  );
  if (validated.valid !== true) {
    throw new Error('Validate definition trả về valid != true.');
  }
  steps.push({ step: 'validate', passed: true, details: 'valid=true' });

  const simulated = asRecord(
    await apiCall(baseUrl, `/workflows/definitions/${definitionId}/simulate`, tenantId, token, {
      method: 'POST',
      body: {
        actions: ['APPROVE'],
        contextJson: { amount: 1000000 }
      }
    })
  );
  if (simulated.success !== true) {
    throw new Error('Simulate definition trả về success != true.');
  }
  steps.push({ step: 'simulate', passed: true, details: 'success=true' });

  const published = asRecord(
    await apiCall(baseUrl, `/workflows/definitions/${definitionId}/publish`, tenantId, token, {
      method: 'POST'
    })
  );
  if (String(published.status ?? '').toUpperCase() !== 'ACTIVE') {
    throw new Error(`Publish trả về status không hợp lệ: ${String(published.status ?? 'unknown')}`);
  }
  steps.push({ step: 'publish', passed: true, details: 'status=ACTIVE' });

  const archived = asRecord(
    await apiCall(baseUrl, `/workflows/definitions/${definitionId}/archive`, tenantId, token, {
      method: 'POST'
    })
  );
  if (String(archived.status ?? '').toUpperCase() !== 'ARCHIVED') {
    throw new Error(`Archive trả về status không hợp lệ: ${String(archived.status ?? 'unknown')}`);
  }
  steps.push({ step: 'archive', passed: true, details: 'status=ARCHIVED' });

  const finishedAt = new Date().toISOString();
  console.log(
    JSON.stringify(
      {
        smoke: 'workflow-definition-lifecycle',
        startedAt,
        finishedAt,
        baseUrl,
        tenantId,
        definitionId,
        workflowCode: uniqueCode,
        steps,
        passed: true
      },
      null,
      2
    )
  );
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`[smoke-workflow-definition-lifecycle] ${message}`);
  process.exitCode = 1;
});
